#!/usr/bin/env bash
set -e

echo "=========================================="
echo " Local Load Testing Guide"
echo "=========================================="
echo ""
echo "--- Safe Defaults ---"
echo "  Default rate: 50 events/sec (~180K orders/hour)"
echo "  This is safe for any machine with 4GB+ Docker RAM."
echo ""
echo "--- Scaling to 500 events/sec ---"
echo "  1. Edit sql/04_generate_orders.sql"
echo "     Change: 'rows-per-second' = '500'"
echo "  2. Or use the commented template in sql/07_large_volume_simulation.sql"
echo ""
echo "--- Scaling to 5000 events/sec ---"
echo "  1. Scale TaskManagers first:"
echo "     docker compose up --scale taskmanager=3 -d"
echo "  2. Increase checkpoint interval to reduce overhead:"
echo "     SET 'execution.checkpointing.interval' = '60s';"
echo "  3. Use 'rows-per-second' = '5000' in the faker source"
echo "  4. Monitor Docker memory: docker stats"
echo ""
echo "--- Metrics to Watch ---"
echo "  - Flink Web UI: http://localhost:8083"
echo "    * Backpressure (must be LOW or OK)"
echo "    * Checkpoint duration (should be < 10s)"
echo "    * Records in/out per operator"
echo "  - Docker stats:"
echo "    docker stats --format 'table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}'"
echo "  - Row counts (run in SQL client, batch mode):"
echo "    SELECT COUNT(*) FROM orders_raw;"
echo "    SELECT COUNT(*) FROM orders_enriched;"
echo ""
echo "--- Scaling Customer/Product Cardinality ---"
echo "  python datagen/generate_seed_data.py --customers 200 --output sql/03_seed_data.sql"
echo "  python datagen/generate_seed_data.py --customers 200 --emit-ids"
echo "  (Update the Options.option in sql/04_generate_orders.sql with new IDs)"
echo ""
echo "--- What NOT to Do Locally ---"
echo "  - Don't exceed 5000 events/sec with 1 TaskManager"
echo "  - Don't run SELECT * on large tables during high load"
echo "  - Don't ignore backpressure warnings in Flink UI"
echo "  - Don't allocate less than 4GB RAM to Docker"
echo ""
