-- =============================================================================
-- 03_seed_data.sql
-- Auto-generated by datagen/generate_seed_data.py
-- Generated: 2026-05-02 14:56:50
-- Customers: 20, Products: 30
-- =============================================================================

USE CATALOG fluss_catalog;
USE ecommerce;

SET 'execution.runtime-mode' = 'batch';
SET 'table.dml-sync' = 'true';

-- =============================================================================
-- CUSTOMER PROFILES (20 records)
-- =============================================================================

INSERT INTO customer_profile VALUES
    ('CUS-bc3f5734', 'Rohan Shah', 'Mumbai', 'BRONZE', DATE '2025-11-09', TIMESTAMP '2025-11-09 10:30:00'),
    ('CUS-244579ca', 'Meera Naidu', 'Chennai', 'BRONZE', DATE '2025-07-30', TIMESTAMP '2025-07-30 10:30:00'),
    ('CUS-ae9a6504', 'Rahul Jain', 'Mumbai', 'BRONZE', DATE '2025-06-18', TIMESTAMP '2025-06-18 10:30:00'),
    ('CUS-7f150bce', 'Megha Jain', 'Mumbai', 'PLATINUM', DATE '2023-12-18', TIMESTAMP '2023-12-18 10:30:00'),
    ('CUS-8e8e0349', 'Ankit Jain', 'Pune', 'SILVER', DATE '2025-02-06', TIMESTAMP '2025-02-06 10:30:00'),
    ('CUS-6ece6507', 'Neha Nair', 'Chennai', 'PLATINUM', DATE '2024-04-22', TIMESTAMP '2024-04-22 10:30:00'),
    ('CUS-96aac47f', 'Ankit Menon', 'Bengaluru', 'BRONZE', DATE '2025-11-13', TIMESTAMP '2025-11-13 10:30:00'),
    ('CUS-b3d3f099', 'Trisha Verma', 'Delhi', 'SILVER', DATE '2025-06-12', TIMESTAMP '2025-06-12 10:30:00'),
    ('CUS-27fe0d2e', 'Harsh Thakkar', 'Ahmedabad', 'BRONZE', DATE '2026-02-09', TIMESTAMP '2026-02-09 10:30:00'),
    ('CUS-6bf9b9ec', 'Sakshi Iyer', 'Bengaluru', 'SILVER', DATE '2025-06-16', TIMESTAMP '2025-06-16 10:30:00'),
    ('CUS-2ea26c14', 'Abhishek Malhotra', 'Delhi', 'GOLD', DATE '2024-05-06', TIMESTAMP '2024-05-06 10:30:00'),
    ('CUS-168bc0ab', 'Shruti Joshi', 'Pune', 'BRONZE', DATE '2025-11-07', TIMESTAMP '2025-11-07 10:30:00'),
    ('CUS-3fc6fc46', 'Ishaan Verma', 'Delhi', 'BRONZE', DATE '2026-01-11', TIMESTAMP '2026-01-11 10:30:00'),
    ('CUS-b17e412c', 'Nisha Malhotra', 'Delhi', 'SILVER', DATE '2025-05-26', TIMESTAMP '2025-05-26 10:30:00'),
    ('CUS-2af65034', 'Harsh Malhotra', 'Delhi', 'BRONZE', DATE '2026-01-26', TIMESTAMP '2026-01-26 10:30:00'),
    ('CUS-4412e697', 'Megha Naidu', 'Hyderabad', 'PLATINUM', DATE '2024-03-31', TIMESTAMP '2024-03-31 10:30:00'),
    ('CUS-37aadd9e', 'Arjun Menon', 'Bengaluru', 'GOLD', DATE '2024-06-25', TIMESTAMP '2024-06-25 10:30:00'),
    ('CUS-1cc815bd', 'Pallavi Agarwal', 'Delhi', 'PLATINUM', DATE '2023-11-16', TIMESTAMP '2023-11-16 10:30:00'),
    ('CUS-db0f99df', 'Rahul Sharma', 'Delhi', 'SILVER', DATE '2025-03-26', TIMESTAMP '2025-03-26 10:30:00'),
    ('CUS-9af32bee', 'Neha Thakkar', 'Mumbai', 'PLATINUM', DATE '2024-03-13', TIMESTAMP '2024-03-13 10:30:00');

-- =============================================================================
-- PRODUCT CATALOG (30 records)
-- =============================================================================

INSERT INTO product_catalog VALUES
    ('SKU-ELEC-1001', 'iPhone 15 Pro 128GB', 'electronics', 'Apple', 79999.00, 100, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-ELEC-1002', 'Samsung Galaxy S24 Ultra', 'electronics', 'Samsung', 69999.00, 94, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-ELEC-1003', 'Sony WH-1000XM5 Headphones', 'electronics', 'Sony', 24999.00, 123, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-ELEC-1004', 'MacBook Air M3 13-inch', 'electronics', 'Apple', 114999.00, 53, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-ELEC-1005', 'iPad Air 5th Gen 64GB', 'electronics', 'Apple', 54999.00, 87, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-ELEC-1006', 'JBL Flip 6 Bluetooth Speaker', 'electronics', 'JBL', 8999.00, 211, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-FASH-2001', 'Levis 501 Original Fit Jeans', 'fashion', 'Levis', 3499.00, 307, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-FASH-2002', 'Nike Air Max 270 Running Shoes', 'fashion', 'Nike', 8999.00, 197, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-FASH-2003', 'Allen Solly Slim Fit Formal Shirt', 'fashion', 'Allen Solly', 1499.00, 426, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-FASH-2004', 'Zara Pleated Midi Dress', 'fashion', 'Zara', 2999.00, 219, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-FASH-2005', 'Ray-Ban Aviator Classic Sunglasses', 'fashion', 'Ray-Ban', 5999.00, 261, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-FASH-2006', 'Woodland Trekking Boots', 'fashion', 'Woodland', 4499.00, 275, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-GROC-3001', 'Tata Tea Premium 1kg', 'grocery', 'Tata', 399.00, 2432, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-GROC-3002', 'Aashirvaad Superior MP Atta 10kg', 'grocery', 'Aashirvaad', 549.00, 1532, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-GROC-3003', 'Fortune Rice Bran Oil 5L', 'grocery', 'Fortune', 899.00, 1015, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-GROC-3004', 'Maggi 2-Minute Noodles Family Pack', 'grocery', 'Nestle', 299.00, 3095, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-GROC-3005', 'Amul Butter 500g', 'grocery', 'Amul', 275.00, 3947, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BOOK-4001', 'Atomic Habits by James Clear', 'books', 'Penguin', 399.00, 409, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BOOK-4002', 'The Psychology of Money', 'books', 'Jaico', 349.00, 429, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BOOK-4003', 'Ikigai The Japanese Secret', 'books', 'Penguin', 299.00, 554, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BOOK-4004', 'Rich Dad Poor Dad', 'books', 'Plata', 399.00, 356, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BOOK-4005', 'Sapiens A Brief History', 'books', 'Vintage', 499.00, 300, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BEAU-5001', 'Lakme Eyeconic Kajal Deep Black', 'beauty', 'Lakme', 249.00, 979, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BEAU-5002', 'Nivea Cocoa Nourish Body Lotion', 'beauty', 'Nivea', 399.00, 1114, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BEAU-5003', 'Philips BT3211 Beard Trimmer', 'beauty', 'Philips', 1299.00, 456, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-BEAU-5004', 'Forest Essentials Soundarya Wash', 'beauty', 'Forest Essentials', 1175.00, 664, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-SPRT-6001', 'Yonex Nanoray Light 18i Racket', 'sports', 'Yonex', 2999.00, 215, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-SPRT-6002', 'Nike Premier League Flight Football', 'sports', 'Nike', 1499.00, 235, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-SPRT-6003', 'Boldfit Resistance Bands Set', 'sports', 'Boldfit', 599.00, 351, TIMESTAMP '2024-01-01 00:00:00'),
    ('SKU-SPRT-6004', 'Strauss Premium Yoga Mat 6mm', 'sports', 'Strauss', 899.00, 377, TIMESTAMP '2024-01-01 00:00:00');
